// Sitedeki Türkçe metinlerin İngilizce karşılıklarını barındıran tam kapsamlı sözlük
window.enDict = {
    "☕ Kahve Molası ▼": "☕ Coffee Break ▼",
    "⚙️ Ayarlar ▼": "⚙️ Settings ▼",
    "🐍 Müzikal Yılan": "🐍 Musical Snake",
    "🎶 Nota-Man": "🎶 Note-Man",
    "✈️ Ritim Raid": "✈️ Rhythm Raid",
    "🧱 Müzikal Tetris": "🧱 Musical Tetris",
    "📱 Uygulamayı Yükle": "📱 Install App",
    "🧘 Odak": "🧘 Focus",
    "🧹 Düzeni Sıfırla": "🧹 Reset Layout",
    "🗑️ Hafızayı & Kayıtları Temizle": "🗑️ Clear Memory & Tracks",
    "⛶ Tam Ekran": "⛶ Fullscreen",
    "⌨️ Kısayollar": "⌨️ Shortcuts",
    "Solak": "Lefty",
    "Gündüz Modu": "Light Mode",
    "🎸 Gitar Klavyesi Paneli": "🎸 Guitar Fretboard Panel",
    "⚙️ Kontroller & Akor Dizisi": "⚙️ Controls & Progression",
    "Akor ve Ritim Kontrolleri": "Chord & Rhythm Controls",
    "🚀 Pro Mod": "🚀 Pro Mode",
    "KÖK NOTA": "ROOT NOTE",
    "AKOR TÜRÜ": "CHORD TYPE",
    "▶ Çal": "▶ Play",
    "ENSTRÜMAN TINISI": "INSTRUMENT TONE",
    "Akustik Gitar": "Acoustic Guitar",
    "Klasik Gitar (Naylon)": "Classical Guitar (Nylon)",
    "Elektro Gitar (Distorsiyon)": "Electric Guitar (Distortion)",
    "RİTİM KALIBI": "RHYTHM PATTERN",
    "AKOR SESİ": "CHORD VOL",
    "KAPO AYARI": "CAPO SETTING",
    "TRANSPOZE (YARI TON)": "TRANSPOSE",
    "Sıfırla": "Reset",
    "🔄 Farklı Pozisyon / Varyasyon": "🔄 Variation / Position",
    "+ Kutuya Ekle": "+ Add to Box",
    "🎵 Akor Dizisi & Canlı Performans": "🎵 Progression & Live Performance",
    "🎲 İlham Ver": "🎲 Inspire Me",
    "Döngü": "Loop",
    "Temizle": "Clear",
    "▶ Diziyi Çal": "▶ Play Sequence",
    "📝 TAB Çıktısı": "📝 Export TAB",
    "🔗 Link Kopyala": "🔗 Copy Link",
    "📱 QR Kod": "📱 QR Code",
    "🖼️ Kart İndir": "🖼️ Download Card",
    "💡 Solo & Gam Asistanı": "💡 Solo & Scale Assistant",
    "🎸 Akort Cihazı & Metronom": "🎸 Tuner & Metronome",
    "🎙️ Pro DAW Stüdyosu (Kayıt)": "🎙️ Pro DAW Studio (Record)",
    "🔴 Kaydet": "🔴 Record",
    "📂 Ses Aktar": "📂 Import Audio",
    "💾 Projeyi İndir (.akor)": "💾 Export Project (.akor)",
    "📂 Proje Yükle": "📂 Load Project",
    "Tümünü Seç": "Select All",
    "▶ Birlikte Çal": "▶ Play Together",
    "⏹ Durdur / Başa Sar": "⏹ Stop / Rewind",
    "🔗 Birleştir": "🔗 Merge Tracks",
    "🎛️ Mixdown": "🎛️ Mixdown",
    "💿 Radyo Mastering": "💿 Radio Mastering",
    "🗑️ Sil": "🗑️ Delete",
    "Gitar Atölyesi ve AkorStudyo Hakkında": "About Guitar Workshop & AkorStudyo",
    "🎵 Öne Çıkan Özellikleri Keşfet": "🎵 Discover Key Features",
    "Düz Vuruş": "Straight Strum",
    "Vals (3/4'lük)": "Waltz (3/4)",
    "Akdeniz (D-D-U-U-D-U)": "Mediterranean (D-D-U-U-D-U)",
    "Pop/Rock (D-D-U-U-D)": "Pop/Rock (D-D-U-U-D)",
    "Bossa Nova (Bas + Akor)": "Bossa Nova (Bass+Chord)",
    "Country (Alternatif Bas)": "Country (Alt Bass)",
    "Arpej (Yavaş)": "Arpeggio (Slow)",
    "Funk (Staccato / Kesik)": "Funk (Staccato)",
    "Reggae (Off-beat)": "Reggae (Off-beat)",
    "Blues Shuffle": "Blues Shuffle",
    "Flamenco Strum": "Flamenco Strum",
    "Ahşap: Gül": "Wood: Rosewood",
    "Ahşap: Akçaağaç": "Wood: Maple",
    "Ahşap: Abanoz": "Wood: Ebony",
    "🎓 Şarkı Öğren": "🎓 Learn Song",
    "✨ Şarkı Kalıpları...": "✨ Song Patterns...",
    "Pop Hit (Am-F-C-G)": "Pop Hit (Am-F-C-G)",
    "Modern Pop (C-G-Am-F)": "Modern Pop (C-G-Am-F)",
    "12-Bar Blues (A7-D7-E7)": "12-Bar Blues (A7-D7-E7)",
    "Jazz Standardı (Dm7-G7-Cmaj7)": "Jazz Standard (Dm7-G7-Cmaj7)",
    "R&B / Soul (Fmaj7-E7-Am7-C7)": "R&B / Soul (Fmaj7-E7-Am7-C7)",
    "Klasik Rock (E-D-A-E)": "Classic Rock (E-D-A-E)",
    "Anadolu Rock (Dm-C-Bb-Am)": "Anatolian Rock (Dm-C-Bb-Am)",
    "Flamenko / Endülüs (Am-G-F-E)": "Flamenco / Andalusia (Am-G-F-E)",
    "İspanyol Dokunuşu (Em-D-C-B7)": "Spanish Touch (Em-D-C-B7)",
    "50'ler Rock'n Roll (C-Am-F-G)": "50s Rock'n Roll (C-Am-F-G)",
    "Alternatif Rock (G-B-C-Cm)": "Alternative Rock (G-B-C-Cm)",
    "🎸 Özel Akor Kombinasyonu": "🎸 Custom Chord Combination",
    "✨ 🎸 Özel Akor Kombinasyonu": "✨ 🎸 Custom Chord Combination",
    "✨ Özel Akor Dizisi": "✨ Custom Chord Sequence",
    "🌟 Tamamlayıcı (IV)": "🌟 Complementary (IV)",
    "🔥 Çözücü (V)": "🔥 Resolution (V)",
    "🌧️ Hüzünlü (vi)": "🌧️ Melancholic (vi)",
    "🌉 Geçiş (ii)": "🌉 Transition (ii)",
    "☀️ Yükseliş (VI)": "☀️ Uplifting (VI)",
    "⚡ Güçlü (VII)": "⚡ Powerful (VII)",
    "🌌 Karanlık (iv)": "🌌 Dark (iv)",
    "⚓ Kararlı (v)": "⚓ Stable (v)",
    "Akor Pusulası Önerisi:": "Chord Compass Suggestion:",
    "akorundan sonra şunlar harika gider:": "sounds great followed by:",
    "Temel Gam Önerisi": "Basic Scale Suggestion",
    "Tavsiye Edilen Solo Gamı:": "Recommended Solo Scale:",
    "Solo İpucu:": "Solo Tip:",
    "Alternatif İlgili Gam:": "Alternative Related Scale:",
    "Solo Teknikleri:": "Solo Techniques:",
    "🎵 Bu Gamı Klavyede Göster": "🎵 Show Scale on Fretboard",
    "Hüzünlü ve derin bir hava katmak için": "To add a deep, melancholic vibe, hold the",
    "(Kök) notasında uzun durun.": "(Root) note.",
    "Neşeli bir hissiyat için gamın Majör 3'lüsünü vurgulayın.": "For a joyful feel, emphasize the Major 3rd of the scale.",
    "Gamına Geç": "Scale",
    "Gam Türü (Mod):": "Scale Type (Mode):",
    "Ölçü Kalıbı:": "Fretboard Pattern:",
    "Otomatik (Önerilen)": "Auto (Recommended)",
    "Majör Pentatonik": "Major Pentatonic",
    "Minör Pentatonik": "Minor Pentatonic",
    "Ionian (Majör)": "Ionian (Major)",
    "Aeolian (Minör)": "Aeolian (Minor)",
    "1. Pozisyon (Kutu Kalıbı)": "1st Position (Box Pattern)",
    "Tüm Klavye Yayılımı": "Full Fretboard Spread",
    "🎸 Akıllı Akort Cihazı": "🎸 Smart Tuner",
    "Mikrofonu açın ve tellere vurun": "Turn on mic and strike the strings",
    "🎙️ Akort Et": "🎙️ Tune Guitar",
    "🛑 Duraklat": "🛑 Pause",
    "🥁 Davul & Metronom": "🥁 Drum & Metronome",
    "AÇ": "ON",
    "KAPAT": "OFF",
    "Davul Stili": "Drum Style",
    "Metronom (Click)": "Metronome (Click)",
    "Rock Bateri": "Rock Drum Kit",
    "Funk Groove": "Funk Groove",
    "Lo-Fi Chill": "Lo-Fi Chill",
    "Jazz Swing": "Jazz Swing",
    "Hız Antrenörü (+5 BPM / 4 Ölçü)": "Speed Trainer (+5 BPM / 4 Bars)",
    "Ses/Görsel:": "Audio/Visual:",
    "Görsel": "Visual",
    "🎙️ Pro DAW Stüdyosu (Çoklu Kanal Kayıt)": "🎙️ Pro DAW Studio (Multi-Track Record)",
    "Sınırsız kanal ekleyin. Mix ve düzenlemelerinizi yapın.": "Add unlimited tracks. Mix and arrange your recordings.",
    "🥁 Hazır Altyapı Ekle": "🥁 Add Backing Track",
    "🎧 Monitör": "🎧 Monitor",
    "Pro İpucu:": "Pro Tip:",
    "Tertemiz ve güçlü bir ses elde etmek için (akustik sızmayı önlemek adına) mutlaka kulaklık kullanın veya enstrümanınızı ses kartı/jak ile bilgisayara bağlayın.": "To get a clean, powerful sound, make sure to use headphones or connect your instrument via audio interface.",
    "Kayıtlı kanal yok. Yeni bir kayıt başlatın.": "No recorded tracks. Start a new recording.",
    "✂️ Kırp": "✂️ Trim",
    "🪄 Gürleştir": "🪄 Normalize",
    "🔇 Dip Ses": "🔇 Noise Gate",
    "🔪 Böl": "🔪 Split",
    "👯 Klonla": "👯 Clone",
    "🔄 Sıfırla": "🔄 Reset",
    "Bas": "Low",
    "Mid": "Mid",
    "Tiz": "High",
    "Pan": "Pan",
    "Yankı": "Reverb",
    "Gecikme": "Delay",
    "Odak Modu (Canlı Demo):": "Focus Mode (Live Demo):",
    "Ekranda sadece çalıştığınız paneller kalsın! Tek tuşla dikkat dağıtıcı menüleri gizleyerek müziğe odaklanın.": "Keep only the panels you are working on! Hide distracting menus with a single click and focus on the music.",
    "Tını, Ritim ve Kapo (Canlı Demo):": "Tone, Rhythm & Capo (Live Demo):",
    "Akustik, Elektro veya Klasik gitar tınıları seçin, farklı ritim kalıpları (Vals, Pop vb.) uygulayın ve Kapo kullanın.": "Choose Acoustic, Electric, or Classical guitar tones, apply different rhythm patterns (Waltz, Pop, etc.), and use a Capo.",
    "İlham Ver (Canlı Demo):": "Inspire Me (Live Demo):",
    "Nereden başlayacağınızı bilmiyorsanız, akor pusulası rastgele ve uyumlu harika akor kalıpları üretir.": "If you don't know where to start, the chord compass generates random and harmonically great chord progressions.",
    "Gamı Klavyede Göster (Canlı Demo):": "Show Scale on Fretboard (Live Demo):",
    "Seçtiğiniz akora uygun pentatonik veya majör gam formüllerini anında gitar klavyesi üzerine yansıtın.": "Instantly project pentatonic or major scale formulas suitable for your selected chord onto the guitar fretboard.",
    "Akor Pusulası:": "Chord Compass:",
    "Çaldığınız son akora göre \"hangi akorlar harika gider\" önerilerini anında alın.": "Get instant suggestions for \"what chords sound great\" based on the last chord you played.",
    "QR Kod ile Anında Paylaşım:": "Instant Sharing via QR Code:",
    "Akor dizilerini ve metronomu tek tıkla QR koda çevirip saniyeler içinde paylaşın.": "Turn your chord progressions and metronome into a QR code with one click and share in seconds.",
    "Pro DAW Stüdyosu (Çoklu Kanal Kayıt):": "Pro DAW Studio (Multi-Track Record):",
    "Sınırsız kanal açarak tarayıcı üzerinden mikrofonla ses kaydı yapın, altyapılar ekleyin.": "Open unlimited tracks, record audio via microphone through the browser, and add backing tracks.",
    "Akıllı Akort Cihazı (Tuner):": "Smart Tuner:",
    "Gitarınızı en hassas şekilde akort edin. Mikrofon erişimi ile çalışan akort cihazımız her an yanınızda.": "Tune your guitar with the highest precision. Our microphone-enabled tuner is always with you.",
    "Özelleştirilebilir Paneller:": "Customizable Panels:",
    "Arayüzü sürükle-bırak ile düzenleyin. Karmaşa hissederseniz \"Düzeni Sıfırla\" ile başa dönün.": "Organize the interface with drag-and-drop. If it feels cluttered, revert back with \"Reset Layout\".",
    "Kaldığın Yerden Devam Et (Akıllı Hafıza):": "Pick Up Where You Left Off (Smart Memory):",
    "Seçtiğiniz akor dizisi, ritim, BPM ve panel sıralamalarınız kaydedilir.": "Your selected chord progression, rhythm, BPM, and panel orders are saved.",
    "İnternetsiz (Offline) Kullanım (Canlı Demo):": "Offline Usage (Live Demo):",
    "Cihazınızda internet koptuğunda sistem uyarı verir ve kayıpsız çalışmaya devam eder.": "When your device loses internet connection, the system alerts you and continues working seamlessly.",
    "Görsel Metronom ve Bateri (Canlı Demo):": "Visual Metronome & Drums (Live Demo):",
    "Tıklama sesini Rock Bateri veya Lo-Fi ile değiştirin, görsel efektlerle ritmi takip edin.": "Change the click sound to Rock Drums or Lo-Fi, and follow the rhythm with visual effects.",
    "Solak Gitarist Desteği (Canlı Demo):": "Lefty Guitarist Support (Live Demo):",
    "Solak müzisyenler için tek tuşla tüm klavye ve akor diyagramlarını ters çevirebilirsiniz.": "For left-handed musicians, you can flip the entire fretboard and chord diagrams with a single click.",
    ", müzisyenler için tasarlanmış": ", designed for musicians, is a free",
    "ve kapsamlı bir eğitim platformudur. Herhangi bir program kurmadan": "and a comprehensive training platform. Without installing any software, you can perform",
    "işlemini gerçekleştirebilir,": "operations directly from the browser, and practice rhythm with the",
    "ile ritim çalışabilirsiniz. Amacımız,": ". Our goal is to allow you to record your musical ideas instantly as multi-tracks thanks to our",
    "asistanımız ve interaktif klavyemiz sayesinde müzikal fikirlerinizi anında çoklu kanal olarak kaydetmenizi sağlamaktır.": "assistant and interactive fretboard.",
    "↑ Yukarı Çık": "↑ Scroll to Top",
    "Basit Görünüm Aktif": "Simple View Active",
    "✨ Odak Modu (Canlı Demo):": "✨ Focus Mode (Live Demo):",
    "✨ Tını, Ritim ve Kapo (Canlı Demo):": "✨ Tone, Rhythm & Capo (Live Demo):",
    "✨ İlham Ver (Canlı Demo):": "✨ Inspire Me (Live Demo):",
    "✨ Gamı Klavyede Göster (Canlı Demo):": "✨ Show Scale on Fretboard (Live Demo):",
    "✨ Akor Pusulası:": "✨ Chord Compass:",
    "✨ QR Kod ile Anında Paylaşım:": "✨ Instant Sharing via QR Code:",
    "✨ Pro DAW Stüdyosu (Çoklu Kanal Kayıt):": "✨ Pro DAW Studio (Multi-Track Record):",
    "✨ Akıllı Akort Cihazı (Tuner):": "✨ Smart Tuner:",
    "✨ Özelleştirilebilir Paneller:": "✨ Customizable Panels:",
    "✨ Kaldığın Yerden Devam Et (Akıllı Hafıza):": "✨ Pick Up Where You Left Off (Smart Memory):",
    "✨ İnternetsiz (Offline) Kullanım (Canlı Demo):": "✨ Offline Usage (Live Demo):",
    "✨ Görsel Metronom ve Bateri (Canlı Demo):": "✨ Visual Metronome & Drums (Live Demo):",
    "✨ Solak Gitarist Desteği (Canlı Demo):": "✨ Lefty Guitarist Support (Live Demo):",
    " Tertemiz ve güçlü bir ses elde etmek için (akustik sızmayı önlemek adına) mutlaka ": " To get a clean, powerful sound (to prevent acoustic bleed), make sure to use ",
    "kulaklık": "headphones",
    " kullanın veya enstrümanınızı ": " or connect your instrument via ",
    "ses kartı/jak": "audio interface/jack",
    " ile bilgisayara bağlayın.": " to the computer.",
    "Gitar Atölyesi (AkorStudyo)": "Guitar Workshop (AkorStudyo)",
    "ücretsiz online DAW stüdyosu": "free online DAW studio",
    "tarayıcı üzerinden gitar akort etme": "guitar tuning via browser",
    "internetsiz çalışan metronom": "offline working metronome",
    "akor pusulası": "chord compass",
    "🎓 İnteraktif Parça Öğreticisi": "🎓 Interactive Song Tutorial",
    "Çıkış": "Exit",
    "Seslendir & İlerle ▶": "Play & Next ▶",
    "İlerle": "Next",
    "✨ 🎲 İlham Ver (Rastgele Kombinasyon)": "✨ 🎲 Inspire Me (Random Combo)",
    "🎲 İlham Ver (Rastgele Kombinasyon)": "🎲 Inspire Me (Random Combo)",
    "💡 Tavsiye Edilen Solo Gamı: ": "💡 Recommended Solo Scale: ",
    "Kalıp: 1. Pozisyon (Önerilen Yol)": "Pattern: 1st Position (Recommended)",
    "Kalıp: Tüm Klavye Yayılımı": "Pattern: Full Fretboard Spread",
    "🎓 Eğitim: Caddelerde Rüzgar (Am-Dm-G-C)": "🎓 Tutorial: Caddelerde Rüzgar (Am-Dm-G-C)",
    "✨ 🎓 Eğitim: Caddelerde Rüzgar (Am-Dm-G-C)": "✨ 🎓 Tutorial: Caddelerde Rüzgar (Am-Dm-G-C)",
    "Oyun Molası": "Game Break",
    "Ses Açık": "Sound On",
    "Ses Kapalı": "Sound Off",
    "Komboları yakala, detonelerden kaç!": "Catch combos, dodge out-of-tune notes!",
    "OYUNCU ADI": "PLAYER NAME",
    "Oyuna Başla": "Start Game",
    "YENİDEN BAŞLA": "RESTART",
    "Tekrar Oyna": "Play Again",
    "Hareket": "Move",
    "Duraklat": "Pause",
    "İkinci Şans!": "Second Chance!",
    "Arkada çalan ve stüdyoda görünen akor hangisi?": "Which chord is playing in the background?",
    "Arkada çalan akor hangisi?": "Which chord is playing?",
    "Yanlış cevaplarsan oyun biter!": "Wrong answer means game over!",
    "Doğru bilirsen alan temizlenir!": "Correct answer clears the board!",
    "Müzikal Yılan": "Musical Snake",
    "Notanı çal, akorları patlat, ritmi yakala!": "Play your note, pop chords, catch the rhythm!",
    "Adalara dikkat et, gece modunda hayatta kal!": "Watch out for islands, survive the night mode!",
    "Skor:": "Score:",
    "MOLA": "PAUSE",
    "Devam etmek için ekrana dokun veya <b>P</b>'ye bas.": "Tap screen or press <b>P</b> to resume.",
    "Devam etmek için <b>P</b>'ye bas.": "Press <b>P</b> to resume.",
    "Devam etmek için <b>Space</b> tuşuna bas veya <b>ekrana dokun</b>.": "Press <b>Space</b> or <b>tap screen</b> to resume.",
    "Eller klavyeye!": "Hands on keyboard!",
    "Hazırlan...": "Get Ready...",
    "Yakalandın! 🛑": "Busted! 🛑",
    "Tekrar oynamak için <b>aşağıya tıkla</b>.": "Click below to play again.",
    "Yeniden oynamak için <b>ENTER</b>'a bas.": "Press <b>ENTER</b> to restart.",
    "İSİMSİZ": "UNNAMED",
    "🎸 Teli titrettin, ses de çıktı. İçin rahatladı mı? Şimdi o cam ekrana dokunmayı bırak da gerçek gitarını eline al!": "🎸 You plucked the string and it made a sound. Feel better now? Stop tapping the glass and grab your real guitar!",
    "👀 Hâlâ ekrana dokunuyorsun... Ekranda nasır tutacak parmakların, git gerçek tel acısı çek biraz!": "👀 Still tapping... You'll get calluses on the screen. Go feel some real string pain!",
    "📱 Tamam, anladık, dokunmatik ekranın çok hassas. Ama burası bir stüdyo, mobil oyun değil. Hadi, al şu gitarı!": "📱 Okay, we get it, your touchscreen works. But this is a studio, not a mobile game. Grab the guitar!",
    "🛑 İnatçısın! Daha fazla ses yok. Gitarı alana kadar protesto ediyorum.": "🛑 Stubborn! No more sound for you. I'm on strike until you pick up a real guitar.",
    "Selam! 🎸": "Welcome! 🎸",
    "Geç ✕": "Skip ✕",
    "Eline gitarını al ve müziğine odaklan. Akor Pusulası, Solo Asistanı, Akort Aleti ve Pro DAW Stüdyosu... 'Pro' etiketleri seni endişelendirmesin; burası her zaman ücretsiz, reklamsız ve üyeliksiz kalacak.": "Grab your guitar and focus on your music. Chord Compass, Solo Assistant, Tuner and Pro DAW Studio... Don't let the 'Pro' tags worry you; this place will always remain free, ad-free, and no sign-up required.",
    "Sen yeter ki keşfet. Eğer müziğinle ön plana çıkarsan, bir gün bizden bahset. Bu bizim tüm emeğimizin karşılığıdır.": "Just explore. If you stand out with your music, just mention us one day. That will be the greatest reward for all our effort.",
    "Başarılar...": "Good luck...",
        "Selam! Yaptığın harika akor dizilerini ve stüdyo ayarlarını cihazında saklıyorum. Merak etme, verilerin stüdyo dışına çıkmaz. Detaylar için ": "Hi! I save your awesome chord progressions and studio settings on your device. Don't worry, your data never leaves the studio. For details, check our ",
        "Gizlilik Politikamıza": "Privacy Policy",
        " göz atabilirsin.": ".",
        "Müziğe Devam 🤘": "Rock On 🤘"
};